import { defineConfig } from 'astro/config';
import tailwind from '@astrojs/tailwind';

// Sitemap is generated by src/pages/sitemap-index.xml.ts (custom endpoint).
// The @astrojs/sitemap plugin currently throws "_routes is undefined" with
// this Astro version, so we hand-roll the XML to keep control.

export default defineConfig({
  site: 'https://freezerbatchcocktails.com',
  integrations: [
    tailwind(),
  ],
  build: {
    inlineStylesheets: 'auto',
  },
});
